#!/usr/bin/env bash
set -euo pipefail

OPENCODE_ADAPTER_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$OPENCODE_ADAPTER_ROOT/../.." && pwd)"
INSTALL_SCOPE="global"
PROJECT_DIR=""

usage() {
  cat <<'USAGE'
Usage:
  install.sh [--global]
  install.sh --local [project-dir]
  install.sh --opencode-home <path>

Options:
  --global                Install into OPENCODE_HOME or ~/.config/opencode. This is the default.
  --local [project]      Install into <project>/.opencode. Defaults to the current directory.
  --opencode-home <path> Install into an explicit opencode config path.
  -h, --help             Show this help.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --global)
      INSTALL_SCOPE="global"
      PROJECT_DIR=""
      shift
      ;;
    --local)
      INSTALL_SCOPE="local"
      if [ "${2:-}" != "" ] && [ "${2#-}" = "$2" ]; then
        PROJECT_DIR="$2"
        shift 2
      else
        PROJECT_DIR="$PWD"
        shift
      fi
      ;;
    --opencode-home)
      if [ "${2:-}" = "" ]; then
        echo "ERROR: --opencode-home requires a path" >&2
        exit 1
      fi
      INSTALL_SCOPE="explicit"
      OPENCODE_HOME="$2"
      PROJECT_DIR=""
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ "$INSTALL_SCOPE" = "local" ]; then
  PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"
  OPENCODE_HOME="$PROJECT_DIR/.opencode"
else
  OPENCODE_HOME="${OPENCODE_HOME:-$HOME/.config/opencode}"
fi

SRC_SKILLS="$REPO_ROOT/skills"
DEST_AGENTS="$OPENCODE_HOME/agents"
MANAGED_SKILLS=(
  "infra-agent-router"
  "devops-sre-infra-troubleshooter"
  "docker-engineer"
  "kubernetes-engineer"
  "argocd-gitops-engineer"
  "observability-engineer"
  "cloudflare-edge-engineer"
  "database-reliability-engineer"
  "aws-cloud-engineer"
  "helm-chart-engineer"
  "terraform-terragrunt-engineer"
  "github-actions-engineer"
  "security-engineer"
)

extract_field() {
  local field="$1"
  local file="$2"
  awk -v field="$field" '
    $0 == "---" {
      marker += 1
      next
    }
    marker == 1 && index($0, field ": ") == 1 {
      sub(field ": ", "")
      print
      exit
    }
  ' "$file"
}

strip_frontmatter() {
  awk '
    NR == 1 && $0 == "---" {
      in_frontmatter = 1
      next
    }
    in_frontmatter && $0 == "---" {
      in_frontmatter = 0
      next
    }
    !in_frontmatter {
      print
    }
  ' "$1"
}

write_agent() {
  local skill_name="$1"
  local skill_file="$SRC_SKILLS/$skill_name/SKILL.md"
  local agent_file="$DEST_AGENTS/$skill_name.md"
  local frontmatter_name
  local description

  if [ ! -f "$skill_file" ]; then
    echo "ERROR: managed skill missing SKILL.md: $skill_file" >&2
    exit 1
  fi

  frontmatter_name="$(extract_field "name" "$skill_file")"
  description="$(extract_field "description" "$skill_file")"

  if [ "$frontmatter_name" != "$skill_name" ]; then
    echo "ERROR: skill name mismatch in $skill_file" >&2
    exit 1
  fi

  if [ "$description" = "" ]; then
    echo "ERROR: skill description missing in $skill_file" >&2
    exit 1
  fi

  {
    echo "---"
    echo "description: |-"
    echo "  $description"
    echo "mode: subagent"
    echo "permission:"
    echo "  edit: ask"
    echo "  bash: ask"
    echo "---"
    echo
    echo "<!-- Generated by agent-infra-skills adapters/opencode. Edit skills/$skill_name/SKILL.md in the source repo instead. -->"
    echo
    strip_frontmatter "$skill_file"
  } > "$agent_file"

  echo "Installed opencode agent: $skill_name"
}

echo "Repo root:      $REPO_ROOT"
echo "Scope:          $INSTALL_SCOPE"
if [ "$INSTALL_SCOPE" = "local" ]; then
  echo "Project:        $PROJECT_DIR"
fi
echo "OPENCODE_HOME:  $OPENCODE_HOME"
echo "Destination:    $DEST_AGENTS"

if [ ! -d "$SRC_SKILLS" ]; then
  echo "ERROR: skills directory not found: $SRC_SKILLS" >&2
  exit 1
fi

mkdir -p "$DEST_AGENTS"

# Install only the managed agent files listed above. Do not delete unmanaged
# opencode agents or overwrite opencode.json.
for skill_name in "${MANAGED_SKILLS[@]}"; do
  write_agent "$skill_name"
done

echo
echo "Done."
echo "Restart opencode to pick up new or changed agents."
